version: '3'
services:
  socialapp:
    build:
      context: ./
      dockerfile: Dockerfile

    container_name: socail_app
    ports:
      - 8000:8000
    volumes:
    - ./:/app/
    command: uvicorn main:app --reload  --host 0.0.0.0 --port 8000

    env_file:
      - ./.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo_conatainer
    env_file:
       - ./.env  
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${db_user}
      MONGO_INITDB_ROOT_PASSWORD: ${db_password}
      MONGO_INITDB_DATABASE: ${db_name}
    volumes:
      - ./mongodata:/data/db
    restart: always
    
  redis:
    image: redis
    container_name: redis_container
    ports: 
     - '6380:6380'
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: always  